# Visualize sequence distributions

In [1]:
execfile('ML_Challenge_data_preprocessing.py')

('Generated X with shape ', (347698, 1000))
('Generated y with shape ', (347698,))


In [2]:
X2 = []
y2 = []
for i, x in enumerate(X):
    if 'N' not in X[i,:]:
        X2.append(x)
        y2.append(y[i])
        
X2 = np.array(X2)
y2 = np.array(y2)
print X2.shape
print y2.shape

(347683, 1000)
(347683,)


In [3]:
# sample for faster iteration
sample_size = 1000
y_sample = y2[0:sample_size]
promoter_idcs = (y_sample == 0).nonzero()[0]
num_promoters = len(promoter_idcs)
enhancer_idcs = (y_sample == 1).nonzero()[0]
num_enhancers = len(enhancer_idcs)

promoter_X = X2[promoter_idcs,]
enhancer_X = X2[enhancer_idcs,]
print promoter_X.shape
print enhancer_X.shape

(881, 1000)
(119, 1000)


In [7]:
promoter_distribution = np.zeros((1000,4))
enhancer_distribution = np.zeros((1000,4))
pairs = {'A':0, 'T': 1, 'C': 2, 'G': 3}
for promoter_obv_idx in range(promoter_X.shape[0]):
    promoter_obv = promoter_X[promoter_obv_idx]
    for p_idx in range(len(promoter_obv)):
        p = promoter_obv[p_idx]
        current_count = promoter_distribution.item((p_idx, pairs[p]))
        promoter_distribution.itemset((p_idx, pairs[p]), current_count+1)

for enhancer_obv_idx in range(enhancer_X.shape[0]):
    enhancer_obv = enhancer_X[enhancer_obv_idx]
    for p_idx in range(len(enhancer_obv)):
        p = enhancer_obv[p_idx]
        current_count = enhancer_distribution.item((p_idx, pairs[p]))
        enhancer_distribution.itemset((p_idx, pairs[p]), current_count+1)
        
print (promoter_distribution/promoter_X.shape[0])[0:10,]
print ''
print (enhancer_distribution/enhancer_X.shape[0])[0:10,]

[[ 0.27241771  0.21566402  0.25766175  0.25425653]
 [ 0.2338252   0.22814983  0.28376844  0.25425653]
 [ 0.20998865  0.2553916   0.25085131  0.28376844]
 [ 0.23269012  0.25312145  0.27355278  0.24063564]
 [ 0.24744608  0.23723042  0.2599319   0.2553916 ]
 [ 0.22360953  0.23155505  0.276958    0.26787741]
 [ 0.2292849   0.19750284  0.29511918  0.27809308]
 [ 0.21679909  0.23041998  0.28717367  0.26560726]
 [ 0.24290579  0.2292849   0.2553916   0.27241771]
 [ 0.25652667  0.22587968  0.27468785  0.24290579]]

[[ 0.31932773  0.27731092  0.21008403  0.19327731]
 [ 0.2605042   0.2605042   0.26890756  0.21008403]
 [ 0.26890756  0.29411765  0.28571429  0.1512605 ]
 [ 0.32773109  0.29411765  0.21008403  0.16806723]
 [ 0.28571429  0.24369748  0.30252101  0.16806723]
 [ 0.29411765  0.25210084  0.2605042   0.19327731]
 [ 0.27731092  0.27731092  0.23529412  0.21008403]
 [ 0.30252101  0.27731092  0.21848739  0.20168067]
 [ 0.27731092  0.30252101  0.15966387  0.2605042 ]
 [ 0.28571429  0.33613445  0.